SystemOrganization addCategory: #'DatabaseCriticsBrowser-Spec'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Spec-Announcements'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Spec-Core'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Spec-Errors'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Spec-Icons'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Spec-Subwidgets'!
