SystemOrganization addCategory: #'DatabaseCritics-Tests'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-Core'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-FalsePositives'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-Rules'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-RulesClassification'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-Severity'!
SystemOrganization addCategory: 'DatabaseCritics-Tests-Thresholds'!
