private - contents
listIconContents
	"Private - Method generated with the content of the file File @ /home/julien/Documents/Umons/Ma 1/Projet/Images/png/dcb/list.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAuElEQVQ4T62TUQ2DQBBEwQFO
qAQclCooVUAdFJRQHFRCJYCDSkAC8y57CeFrr7DJBD5u3u4OR54drPygPwPQSK00SY9UIACM
ldRJH6mWSidoiYDBJrnpeTF5GBOAwsxM8vW4tmcA0PFl44//AOj8NJEDeVydoLACAL4CkN4A
BOmpAGAFzOz/9rj2GRDiXZoNksSIK9C5kRidibz3YAbwM1OnZ7xIQDwVLhKdyYAweU+qU36m
pI77wysaASEvVdsoYAAAAABJRU5ErkJggg=='