SystemOrganization addCategory: #'DatabaseCriticsBrowser-Tests'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-Core'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-FalsePositives'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-Rules'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-RulesClassification'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-Severity'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Tests-Thresholds'!
