DCB help
help
	<dcbHelp: 'Database Critics Browser'>
	<dcbIcon: #icon>
	<dcbOpen: #setOnTop>
	^ 'I am the widget used to browse the result of rules on the model.

My left tree holds the rules classified according to your configurations.
My right list holds the entities violating the rule/group of rule selected in the left tree.
I have a button to mark the entity selected in the right list as a false positive.
I also have a button to inspect the FAMIX entity selected in the right list.'