DCB help
help
	<dcbHelp: 'False positives editor'>
	<dcbIcon: #icon>
	<dcbOpen: #openFalsePositivesManagerEditor>
	^ 'I am the widget used to unmark false positives.

Select the rule for which entities have been marked. Then select the entity to unmark and simply click on the button.

When you have unmark all the rules needed, click the "Apply" or "Ok" button. Else you can cancel your modifications using "Cancel" button.'