SystemOrganization addCategory: #DatabaseCriticsBrowser!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Core'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Errors'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-FalsePositives'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Rules'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-RulesClassification'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Severity'!
SystemOrganization addCategory: 'DatabaseCriticsBrowser-Thresholds'!
