SystemOrganization addCategory: #DatabaseCritics!
SystemOrganization addCategory: 'DatabaseCritics-Core'!
SystemOrganization addCategory: 'DatabaseCritics-Errors'!
SystemOrganization addCategory: 'DatabaseCritics-FalsePositives'!
SystemOrganization addCategory: 'DatabaseCritics-Rules'!
SystemOrganization addCategory: 'DatabaseCritics-RulesClassification'!
SystemOrganization addCategory: 'DatabaseCritics-Severity'!
SystemOrganization addCategory: 'DatabaseCritics-Thresholds'!
