DCB help
help
	<dcbHelp: 'Exporter'>
	<dcbIcon: #icon>
	<dcbOpen: #openExporter>
	^ 'I am the widget used to export the critic performed by the browser as file.
	
The left list contains available exporters. The right contains the exporters chosen.

You can add/remove exporters by moving items from a list to another using the buttons under the lists.

Once you have made your choice, click on the ''Export'' button and choose a directory.

If you changed your mind and do not want to export, click the ''Cancel'' button or close the window.'