DCB help
help
	<dcbHelp: 'Rules chooser'>
	<dcbIcon: #icon>
	<dcbOpen: #openRulesChooser>
	^ 'I am the widget used to choose the rules to test the database schema.

The left list contains available rules. The right list the rules chosen to analyse the database schema.
''Add all'' and ''Remove all'' buttons functions are explicit.

You can add/remove rules by moving items from a list to another using the buttons under the lists.

' , self doNotForgetHelp